::set CFLAGS=-nologo -MT -Ox -DKEY_SCANCODES -DDOUBLE_X -DDOUBLE_Y -D_CRT_SECURE_NO_DEPRECATE  -D_WIN32_WINNT=0x500
set CFLAGS=-nologo -Zi -DKEY_SCANCODES -DDOUBLE_X -DDOUBLE_Y -D_CRT_SECURE_NO_DEPRECATE  -D_WIN32_WINNT=0x500
::-DSYNC_SCREEN_UPDATE
::set CFLAGS=-nologo -Zi -DKEY_SCANCODES -DDOUBLE_X -DDOUBLE_Y -D_CRT_SECURE_NO_DEPRECATE
::set CC=icl
set CLDEPS=cldeps.exe
::set AR=xilib.exe
set AR=lib.exe
set ARFLAGS=-nologo
set RC=rc.exe -DWINVER=0x600
if not exist .obj mkdir .obj
